### ISSUE TITLE
Problems with data preprocessing

### ISSUE THREAD

**Issue by 1sdv** [ict-net/NetGPT#2]
In processing Data Preprocessing for Traffic Understanding Tasks，Why does this error occur when there is a .pcap file in the path:
Traceback (most recent call last):
  File "pre-process/input_generation_understanding.py", line 384, in <module>
    main()
  File "pre-process/input_generation_understanding.py", line 381, in main
    dataset_extract(args.random_seed, args.pcap_path, samples, args.middle_save_path, args.class_num)
  File "pre-process/input_generation_understanding.py", line 311, in dataset_extract
    for train_index, test_index in split_1.split(x_payload, dataset_label):
  File "/home/stu003/.conda/envs/netgpt1/lib/python3.8/site-packages/sklearn/model_selection/_split.py", line 2229, in split
    y = check_array(y, input_name="y", ensure_2d=False, dtype=None)
  File "/home/stu003/.conda/envs/netgpt1/lib/python3.8/site-packages/sklearn/utils/validation.py", line 967, in check_array
    raise ValueError(
ValueError: Found array with 0 sample(s) (shape=(0,)) while a minimum of 1 is required.
Could you please give me a detailed explanation of the function of each path and why an error occurs? Thank you

**Comment by Night-Starry** [comment]
python pre-process/input_generation_generation.py  --pcap_path "data/pcap/" --dataset_dir "data/generation/datasets/" --class_num 17 --middle_save_path "data/generation/result/" --random_seed 01
The storage format of the pcap files should meet the following structure in order to be correctly read.The specified folder should not directly contain pcap files.
![image](https://github.com/user-attachments/assets/5e6cf578-8664-4368-8a28-97d89f412483)

**Comment by Night-Starry** [comment]
> In processing Data Preprocessing for Traffic Understanding Tasks，Why does this error occur when there is a .pcap file in the path: Traceback (most recent call last): File "pre-process/input_generation_understanding.py", line 384, in main() File "pre-process/input_generation_understanding.py", line 381, in main dataset_extract(args.random_seed, args.pcap_path, samples, args.middle_save_path, args.class_num) File "pre-process/input_generation_understanding.py", line 311, in dataset_extract for train_index, test_index in split_1.split(x_payload, dataset_label): File "/home/stu003/.conda/envs/netgpt1/lib/python3.8/site-packages/sklearn/model_selection/_split.py", line 2229, in split y = check_array(y, input_name="y", ensure_2d=False, dtype=None) File "/home/stu003/.conda/envs/netgpt1/lib/python3.8/site-packages/sklearn/utils/validation.py", line 967, in check_array raise ValueError( ValueError: Found array with 0 sample(s) (shape=(0,)) while a minimum of 1 is required. Could you please give me a detailed explanation of the function of each path and why an error occurs? Thank you

python pre-process/input_generation_generation.py  --pcap_path "data/pcap/" --dataset_dir "data/generation/datasets/" --class_num 17 --middle_save_path "data/generation/result/" --random_seed 01
The storage format of the pcap files should meet the following structure in order to be correctly read.The specified folder should not directly contain pcap files.
![image](https://github.com/user-attachments/assets/5e6cf578-8664-4368-8a28-97d89f412483)

**Comment by 1sdv** [comment]
> > In processing Data Preprocessing for Traffic Understanding Tasks，Why does this error occur when there is a .pcap file in the path: Traceback (most recent call last): File "pre-process/input_generation_understanding.py", line 384, in main() File "pre-process/input_generation_understanding.py", line 381, in main dataset_extract(args.random_seed, args.pcap_path, samples, args.middle_save_path, args.class_num) File "pre-process/input_generation_understanding.py", line 311, in dataset_extract for train_index, test_index in split_1.split(x_payload, dataset_label): File "/home/stu003/.conda/envs/netgpt1/lib/python3.8/site-packages/sklearn/model_selection/_split.py", line 2229, in split y = check_array(y, input_name="y", ensure_2d=False, dtype=None) File "/home/stu003/.conda/envs/netgpt1/lib/python3.8/site-packages/sklearn/utils/validation.py", line 967, in check_array raise ValueError( ValueError: Found array with 0 sample(s) (shape=(0,)) while a minimum of 1 is required. Could you please give me a detailed explanation of the function of each path and why an error occurs? Thank you
> 
> python pre-process/input_generation_generation.py --pcap_path "data/pcap/" --dataset_dir "data/generation/datasets/" --class_num 17 --middle_save_path "data/generation/result/" --random_seed 01 The storage format of the pcap files should meet the following structure in order to be correctly read.The specified folder should not directly contain pcap files. ![image](https://private-user-images.githubusercontent.com/132438765/386083844-5e6cf578-8664-4368-8a28-97d89f412483.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE1ODQ4OTksIm5iZiI6MTczMTU4NDU5OSwicGF0aCI6Ii8xMzI0Mzg3NjUvMzg2MDgzODQ0LTVlNmNmNTc4LTg2NjQtNDM2OC04YTI4LTk3ZDg5ZjQxMjQ4My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExNFQxMTQzMTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00MzA5MTczMjFhMjg5ZGNkOTI5OWIxN2ViYTAzY2I1YzUwODBkM2RmZTk2ZWY4OTkyMGVmN2Y2YWRmMzNmMjY3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.ZdkVtfxqIn326TgVUmuhqVtaf7bctVBboS8x7b2L5T0)

Hello, thank you for your answer, but after I followed your steps, I ran the command:
python3 pre-process/input_generation_understanding.py   --pcap_path "/home/stu003/lcc/xiang_mu/NetGPT-master/data_pcap/" \
                                                        --dataset_dir "/home/stu003/lcc/xiang_mu/NetGPT-master/data/pre_data/understanding/datasets/" \
                                                        --class_num 2 \
                                                        --middle_save_path "/home/stu003/lcc/xiang_mu/NetGPT-master/data/pre_data/understanding/result/" \
                                                        --random_seed 01
How can I solve this problem? Thank you.
There is still a problem, it seems that only 2 samples are processed:
![read-data](https://github.com/user-attachments/assets/d329a339-8606-4353-98f0-9f3105df8053)
![data](https://github.com/user-attachments/assets/08b8d5e8-bbbe-411b-af9f-19fcb495486f)

**Comment by 1sdv** [comment]
> > In processing Data Preprocessing for Traffic Understanding Tasks，Why does this error occur when there is a .pcap file in the path: Traceback (most recent call last): File "pre-process/input_generation_understanding.py", line 384, in main() File "pre-process/input_generation_understanding.py", line 381, in main dataset_extract(args.random_seed, args.pcap_path, samples, args.middle_save_path, args.class_num) File "pre-process/input_generation_understanding.py", line 311, in dataset_extract for train_index, test_index in split_1.split(x_payload, dataset_label): File "/home/stu003/.conda/envs/netgpt1/lib/python3.8/site-packages/sklearn/model_selection/_split.py", line 2229, in split y = check_array(y, input_name="y", ensure_2d=False, dtype=None) File "/home/stu003/.conda/envs/netgpt1/lib/python3.8/site-packages/sklearn/utils/validation.py", line 967, in check_array raise ValueError( ValueError: Found array with 0 sample(s) (shape=(0,)) while a minimum of 1 is required. Could you please give me a detailed explanation of the function of each path and why an error occurs? Thank you
> 
> python pre-process/input_generation_generation.py --pcap_path "data/pcap/" --dataset_dir "data/generation/datasets/" --class_num 17 --middle_save_path "data/generation/result/" --random_seed 01 The storage format of the pcap files should meet the following structure in order to be correctly read.The specified folder should not directly contain pcap files. ![image](https://private-user-images.githubusercontent.com/132438765/386083844-5e6cf578-8664-4368-8a28-97d89f412483.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE1OTEzNDcsIm5iZiI6MTczMTU5MTA0NywicGF0aCI6Ii8xMzI0Mzg3NjUvMzg2MDgzODQ0LTVlNmNmNTc4LTg2NjQtNDM2OC04YTI4LTk3ZDg5ZjQxMjQ4My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExNFQxMzMwNDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kN2Y2ZDE4ZTFhNDZkOTIyNzhiYmM0Zjg5ZWU5YWExMDQwMDVmNTUzMjljYTU5ZjMyMjJhZGQ0YzE2YWU0ZWMxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.gPSW63biqI3Lea6_hM8AMRE9GBweiVJcurRhyMMC25c)

Thank you very much for your reply, all best.
